### ISSUE TITLE
wait_for_nic should have a timeout

### ISSUE THREAD

**Issue by egernst** [clearcontainers/hyperstart#10]
We should add a timeout and fail gracefully if we cannot find the nic that is supplied to us from the runtime.  Today, if the nic cannot be found, there is no mention of this in any logs, and after a couple of minutes it is docker that kills it due to timeout.

**Comment by jcvenegas** [comment]
@egernst this timeout should be specified in in the json payload? 
Also, If hyperstart is not able to find the nic, sounds like a bug to me ... 

The other option is to timeout all the request from the runtime side.

**Comment by egernst** [comment]
@jcvenegas - I agree that if hyperstart cannot find the nic it is a bug -- I'd like some kind of assert in that situation rather than just silently failing.  This makes debug much easier, especially when we're dealing with something that deals with assumptions and guessing (ie, interface device name provided by qemu).

If you timeout on the runtime side, I don't think you'll have much information other than create-pod failed (not why or where).

**Comment by dlespiau** [comment]
@jcvenegas We should at least have a message on the console/proxy logs telling that hyperstart is waiting for interface "%s" and messages with the names of the interface from the uevents.

@egernst would the above enough? we are "covered" by the docker timeout already it seems, if the last message from hyperstart is "waiting for interface %s" it's hopefully a good enough clue why the thing is timing out?

**Comment by egernst** [comment]
@dlespiau -- yeah -- a clue would certainly be a step in the right direction and would meet my need.

**Comment by egernst** [comment]
wait-for-nic is no longer used since we moved to using mac address to identify the network, so this can be closed.
