### ISSUE TITLE
Make default branch the 'live' one

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/hyperstart#22]
Can we make the default branch for this github project the one we actually build/use - and then I can add/clarify some more documentation to make it clear how to build the binary, without having to merge things into the 'master' branch etc.
Current active branch is '0.7.0-clearcontainers' I believe.

**Comment by dlespiau** [comment]
I don't have those powers, @sameo has though. It think it should just be matter of changing the "default" branch in the branch settings:

> The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.

**Comment by gorozco1** [comment]
+1 on @dlespiau comment

**Comment by sameo** [comment]
Default branch is now 0.7.0.
